// Dados oficiais dos médicos da Bloom Maternity usados pelo front-end como fallback
// e para manter os perfis corretos mesmo quando a API não estiver rodando.
window.BLOOM_DOCTORS = [
  {
    id: 1,
    nome: 'Dr. Gustavo Henrique Martins',
    crm: '145987-SP',
    rqe: '45210',
    especialidade: 'Reprodução Humana',
    foto: '../assets/images/dr-gustavo-henrique-martins.png',
    resumo: 'Fertilidade do casal, inseminação artificial e fertilização in vitro.',
    descricao: 'Especialista em Reprodução Humana, com foco em investigação da infertilidade, fertilidade do casal, inseminação artificial e fertilização in vitro. Atua com acolhimento, planejamento individualizado e linguagem clara em todas as etapas do tratamento.',
    formacao: ['Medicina pela USP', 'Especialização em Reprodução Assistida'],
    areas: ['Fertilidade do casal', 'Inseminação artificial', 'Fertilização in vitro (FIV)', 'Preservação da fertilidade'],
    experiencia: ['Atendimento em reprodução humana assistida', 'Acompanhamento de casais em investigação de infertilidade', 'Planejamento terapêutico individualizado'],
    avaliacao: 4.9,
    total_avaliacoes: 128,
    experiencia_anos: 12,
    disponivel: true
  },
  {
    id: 2,
    nome: 'Dr. Ricardo Almeida Costa',
    crm: '132456-SP',
    rqe: '38764',
    especialidade: 'Medicina Fetal e Ultrassonografia',
    foto: '../assets/images/dr-ricardo-almeida-costa.png',
    resumo: 'Ultrassom morfológico, acompanhamento fetal e gestação de risco.',
    descricao: 'Especialista em Medicina Fetal e Ultrassonografia, com atuação em ultrassom morfológico, acompanhamento fetal e gestação de risco. Realiza avaliações detalhadas com tecnologia de imagem e comunicação humanizada.',
    formacao: ['Medicina pela UNICAMP', 'Residência em Ginecologia e Obstetrícia', 'Fellowship em Medicina Fetal'],
    areas: ['Ultrassom morfológico', 'Acompanhamento fetal', 'Gestação de risco', 'Doppler obstétrico'],
    experiencia: ['Diagnóstico pré-natal avançado', 'Rotina de medicina fetal', 'Acompanhamento de gestações de alto risco'],
    avaliacao: 4.8,
    total_avaliacoes: 95,
    experiencia_anos: 10,
    disponivel: true
  },
  {
    id: 3,
    nome: 'Dra. Fernanda Ribeiro Alves',
    crm: '149876-SP',
    rqe: '49872',
    especialidade: 'Fertilidade e Ginecologia Endócrina',
    foto: '../assets/images/dra-fernanda-ribeiro-alves.png',
    resumo: 'Hormônios femininos, infertilidade e menopausa.',
    descricao: 'Especialista em Fertilidade e Ginecologia Endócrina, dedicada ao cuidado hormonal feminino, infertilidade e menopausa. Atua em consultas preventivas, orientação reprodutiva e equilíbrio hormonal.',
    formacao: ['Medicina pela UNIFESP', 'Pós-graduação em Reprodução Humana'],
    areas: ['Hormônios femininos', 'Infertilidade', 'Menopausa', 'Ginecologia endócrina'],
    experiencia: ['Avaliação hormonal feminina', 'Tratamento de infertilidade', 'Acompanhamento de menopausa e climatério'],
    avaliacao: 4.9,
    total_avaliacoes: 87,
    experiencia_anos: 8,
    disponivel: true
  },
  {
    id: 4,
    nome: 'Dra. Mariana Costa Ferreira',
    crm: '181654-SP',
    rqe: '61204',
    especialidade: 'Obstetrícia e Parto Humanizado',
    foto: '../assets/images/dra-mariana-costa-ferreira.png',
    resumo: 'Gestação, parto normal, puerpério e amamentação.',
    descricao: 'Especialista em Obstetrícia e Parto Humanizado, com atendimento voltado para gestação, parto normal, puerpério e amamentação. Valoriza escuta ativa, segurança clínica e protagonismo da paciente.',
    formacao: ['Medicina pela PUC-SP', 'Residência na Santa Casa de São Paulo', 'Certificação em Assistência ao Parto Humanizado'],
    areas: ['Gestação', 'Parto normal', 'Puerpério', 'Amamentação'],
    experiencia: ['Pré-natal humanizado', 'Assistência ao parto', 'Acompanhamento no pós-parto'],
    avaliacao: 5.0,
    total_avaliacoes: 156,
    experiencia_anos: 15,
    disponivel: true
  },
  {
    id: 5,
    nome: 'Dra. Ana Carolina Mendes',
    crm: '154789-SP',
    rqe: '55432',
    especialidade: 'Ginecologia e Obstetrícia',
    foto: '../assets/images/dra-ana-carolina-mendes.png',
    resumo: 'Pré-natal, parto humanizado, contracepção e saúde feminina.',
    descricao: 'Especialista em Ginecologia e Obstetrícia, com atuação em pré-natal, parto humanizado, contracepção e saúde feminina. Oferece acompanhamento integral em diferentes fases da vida da mulher.',
    formacao: ['Medicina pela Universidade de São Paulo (USP)', 'Residência no Hospital das Clínicas – FMUSP', 'Título FEBRASGO / AMB'],
    areas: ['Pré-natal', 'Parto humanizado', 'Contracepção', 'Saúde feminina'],
    experiencia: ['Consultas ginecológicas preventivas', 'Acompanhamento obstétrico', 'Planejamento familiar'],
    avaliacao: 4.9,
    total_avaliacoes: 142,
    experiencia_anos: 11,
    disponivel: true
  }
];
